// Generated by Wrangler by running `wrangler types --env-interface CloudflareEnv env.d.ts`

interface CloudflareEnv {
	CLOUDINARY_CLOUD_NAME: string;
	CLOUDINARY_API_KEY: string;
	CLOUDINARY_API_SECRET: string;
	NEXT_PUBLIC_SITE_URL: string;
	MAILERLITE_API_KEY: string;
	MAILERLITE_GROUP_ID: string;
	NEXT_PUBLIC_TURNSTILE_SITE_KEY: string;
	TURNSTILE_SECRET_KEY: string;
	SLACK_WEBHOOK_URL: string;
}
