// app/layout.tsx
import './globals.css'
import { ReactNode } from 'react';

export const metadata = {
  title: 'My Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: ReactNode }) {
  return (
    <html lang="en">
      <body>
        <div className="container">
          {children}
        </div>
      </body>
    </html>
  );
}
